### ISSUE TITLE
Increase documentation

### ISSUE THREAD

**Issue by CharGrnmn** [pugjs/pug-loader#25]
Terrific plugin, and I have immense thanks for your creating it. I am having a bit of trouble of using it. I have included it as a loader and requiring it in my index.js. http://stackoverflow.com/questions/32633472/how-does-one-target-a-template-function-in-webpack-using-jade-loader-for-instan

Perhaps we can put in a bit more detail of how to use it. I would be more than happy to pay for more documentation. Feel free to reach out.

**Comment by colelawrence** [comment]
Jade-loader is really good for templates, but it is not so common a practice to use webpack build system to generate html files.

I assume you are referring to something that the [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin) in combination with [jade-html-loader](https://github.com/bline/jade-html-loader) would accomplish. based on [Issue 15](https://github.com/webpack/jade-loader/issues/15)

``` javascript
var ExtractTextPlugin = require("extract-text-webpack-plugin");
module.exports = {
    module: {
        loaders: [
            { test: /^index\.jade$/, loader: ExtractTextPlugin.extract("jade-html-loader") }
        ]
    },
    plugins: [
        new ExtractTextPlugin("index.html")
    ]
}
```

**Comment by CharGrnmn** [comment]
Interesting, I used jade-html-loader, and found it to not work to my liking based on two reasons:
1. I need different output channels for my html than my js. (webpack by default only has one so I decided to go back and stick with the system)
2. I would have to learn the api to prettify the html, which documentation wasn't so great at. 

The above being said, would you say that webpack at this time, or this loader in particular rather, is mostly for individuals using mv's such as React?

**Comment by colelawrence** [comment]
Personally, for simplicity of project structure, I try to use webpack strictly for JavaScript module management. Then, I will use gulp for my CSS and HTML pipelines.

In [my current SPA AngularJS project](https://github.com/ZombieHippie/GoCourseSort/tree/master/www), I don't generate any html files, I have a simple index file which loads the `bundle.js` and `bundle.css`. If I were developing a multiple page app, I would be developing it with a Sencha Connect (Express JS) server in conjunction with jade as a render engine.

**Comment by CharGrnmn** [comment]
Awesome, will definitely take a look at the project. Ok, so one last question, in other words my build system for gulp https://github.com/CharlieGreenman/Gulp-with-foundation-and-sass. Really does not have to use Webpack, nor should it be doing so? Any recommendations would be incredibly appreciated.

**Comment by colelawrence** [comment]
@CharlieGreenman looking at your project, I would judge that you would only benefit from webpack if you truly utilize it's capabilities.

I expected that you were rebasing your project from RequireJS to Webpack, because Webpack is kind of an awesome hugely modular version of the RequireJS project.

Webpack is kind of like the node.js `node_modules` package system for the browser. So, in my project I can write:

``` babel
var $ = require('jquery')

$.ready(()=> {
  console.log("do stuff")
})
```

and Webpack can generate a bundle.js file that includes jquery in my package, but does not export it globally (to the window scope).
Which can do fantastic things for minificaton for example.

I would tell you to look over the [react-starter](https://github.com/webpack/react-starter), but the webpack.config.js is very complex for learning from. But you can draw some insight from [some of the source files](https://github.com/webpack/react-starter/blob/master/app/mainRoutes.jsx), because they demonstrate how powerful webpack can be for codebase organization.

**Comment by TimothyGu** [comment]
@CharlieGreenman, do you still have a question about this? I'll close the issue but feel free to comment or email me (check my GitHub page for email address) if you need some more help.
