### ISSUE TITLE
Variable not shared

### ISSUE THREAD

**Issue by sayll** [pugjs/pug-loader#47]
```
//  var.jade
-var path='test';

// meta.jade
include ./var.jade;

// index.jade
doctype html
html
    head
        include ./meta.jade
    body
        include ./header
// header.jade
p #{path}
```

**Comment by TimothyGu** [comment]
This is because pug-loader, according to Webpack tradition, uses Webpack's `require` when `include` is involved. For this reason, the child file will not have access to the parent's variables, like it usually does. To fix this, you'll have to set the variable as a part of the locals object, which is passed through the includes.

``` pug
//  var.jade
-locals.path='test';

// meta.jade
include ./var.jade;

// index.jade
doctype html
html
    head
        include ./meta.jade
    body
        include ./header
// header.pug
p #{path}
```

**Comment by sayll** [comment]
thanks

**Comment by TimothyGu** [comment]
Check out #54. We've decided to make your original code work again.
